//LOGIN
export const MODIFICA_EMAIL = 'modifica_email'
export const MODIFICA_SENHA = 'modifica_senha'
export const FALHA_LOGIN = 'falha_login'
export const LOADING_LOGIN = 'loading_login'
//F1
export const MODIFICA_TURNO = 'modifica_turno'
export const MODIFICA_MICROAREA = 'modifica_microarea'
export const MODIFICA_TIPO_IMOVEL = 'modifica_tipo_imovel'
export const MODIFICA_NUMERO_PRONTUARIO = 'modifica_numero_prontuario'
export const MODIFICA_CNS = 'modifica_cns'
export const MODIFICA_DATA = 'modifica_data'
export const MODIFICA_SEXO = 'modifica_sexo'
export const MODIFICA_PESO = 'modifica_peso'
export const MODIFICA_ALTURA = 'modifica_altura'
export const MODIFICA_VISITA_COMPARTILHADA = 'modifica_visita_compartilhada'