//F1P1
export const MODIFICA_TURNO = 'modifica_turno'
export const MODIFICA_MICROAREA = 'modifica_microarea'
export const MODIFICA_TIPO_IMOVEL = 'modifica_tipo_imovel'
export const MODIFICA_NUMERO_PRONTUARIO = 'modifica_numero_prontuario'
export const MODIFICA_CNS = 'modifica_cns'
export const MODIFICA_DATA = 'modifica_data'
export const MODIFICA_SEXO = 'modifica_sexo'
export const MODIFICA_PESO = 'modifica_peso'
export const MODIFICA_ALTURA = 'modifica_altura'
export const MODIFICA_VISITA_COMPARTILHADA = 'modifica_visita_compartilhada'
//F1P2
export const MODIFICA_CADASTRAMENTO_ATUALIZACAO = 'modifica_cadastramento_atualizacao'
export const MODIFICA_VISITA_PERIODICA = 'modifica_visita_periodica'
export const MODIFICA_CONSULTA = 'modifica_consulta'
export const MODIFICA_EXAME = 'modifica_exame'
export const MODIFICA_VACINA = 'modifica_vacina'
export const MODIFICA_BOLSA_FAMILIA = 'modifica_bolsa_familia'
//F1P3
export const MODIFICA_GESTANTE = 'modifica_gestante'
export const MODIFICA_PUEPERA = 'modifica_puepera'
export const MODIFICA_RECEM_NASCIDO = 'modifica_recem_nascido'
export const MODIFICA_CRIANCA = 'modifica_crianca'
export const MODIFICA_DESNUTRICAO = 'modifica_desnutricao'
export const MODIFICA_REABILITACAO_DEFICIENTE = 'modifica_reabilitacao_deficiente'
export const MODIFICA_HIPERTENSAO = 'modifica_hipertensao'
export const MODIFICA_DIABETES = 'modifica_diabetes'
export const MODIFICA_ASMA = 'modifica_asma'
export const MODIFICA_DPOC_ENFISEMA = 'modifica_dpoc_enfisema'
export const MODIFICA_CANCER = 'modifica_cancer'
export const MODIFICA_DOENCA_CRONICA = 'modifica_doenca_cronica'
export const MODIFICA_HANSENIASE = 'modifica_hanseniase'
export const MODIFICA_TUBERCULOSE = 'modifica_tuberculose'
//F1P4
export const MODIFICA_SINTOMATICOS_RESPIRATORIOS = 'modifica_sintomaticos_respiratorios'
export const MODIFICA_TABAGISTA = 'modifica_tabagista'
export const MODIFICA_DOMICILIADOS_ACAMADOS = 'modifica_domiciliados_acamados'
export const MODIFICA_VULNERABILIDADE_SOCIAL = 'modifica_vulnerabilidade_social'
export const MODIFICA_CONDICIONALIDADES_BOLSA_FAMILIA = 'modifica_condicionalidades_bolsa_família'
export const MODIFICA_SAUDE_MENTAL = 'modifica_saude_mental'
export const MODIFICA_USUARIO_ALCOOLICO = 'modifica_usuario_alcoolico'
export const MODIFICA_USUARIO_DROGAS = 'modifica_usuario_drogas'